### PR TITLE
Username and email case sensitivity

### PR DESCRIPTION
**Pull request by DonMcNamara**
This is a breaking change. It adds UsernameLower and EmailLower properties to the user BSON document. I also extracted the query building logic to private methods.

### CODE REVIEW

**Comment by Madd0g** [comment]
Hey, Thanks for the fix.
I noticed that partial username matches don't work (for example - in `FindUsersByName`).

Maybe that's one place where `QueryUsername` shouldn't be used with `Query.EQ`?

Thanks

**Comment by Madd0g** [comment]
Also (not that anyone cares, lol) - when using a different case to login, the session and everything uses the lowercase (or whatever cOmBiNAtion the user typed, instead of the value in the username field)

EDIT: Ahh... it looks like the problem comes from the default MVC controller and not this.

**Comment by DonMcNamara** [comment]
There is another mongodb provider implementation here: http://code.google.com/p/mongoproviders/  It seems to be more mature, but I think it also has the case sensitivity issue.

**Comment by Madd0g** [comment]
Thanks, I saw that one, I just implemented your case-insensitive solution (except I changed FindUsersByName to support partial queries). Thanks for that.

**Comment by osuritz** [comment]
@DonMcNamara you might be interested to know that I integrated your pull request into my own fork of this project: https://github.com/osuritz/MongoDB.Web/  My version essentially adds the ability to specify the connection string through the AppSettings version (useful on platforms like AppHarbor).

I ran into an issue where if "UserA" and "usera" are both added to a MembershipUserCollection, the framework throws an exception. So I needed a way to make usernames case insensitive and thus added your pull request to my own project since this repo doesn't seem to be updated anymore.

**Comment by freshlogic** [comment]
Hey guys. Sorry for the lack of response for a couple years on this project. There was some confusion with my previous employment at Woot/Amazon as to whether this project was approved by their open source committee. Prevented me from maintaining this project after I originally released it.

I recently quit my job at Amazon which gives me the ability to more aggressively maintain things going forward. I appreciate everyone's help keeping the project somewhat relevant for those looking for a MongoDB solution for ASP.NET providers.

I've merged in a couple pull requests, updated the MongoDB driver, made the usernames and email addresses case sensitive, and cleaned up a few things. I'll be cutting a new NuGet package soon.

**Pull request closed without merging**
