### PR TITLE
Pickup connection string from appSettings

### PR DESCRIPTION
**Pull request by osuritz**
I've added the ability to pickup connection string from an appSettings entry. This makes MongoDB.Web work with a platform like AppHarbor that dynamically inserts the connection string to the MongoDB add-on in that section.

### CODE REVIEW

**Comment by DonMcNamara** [comment]
I really like the connection string change. Any ideas why it isn't being merged in?

**Comment by osuritz** [comment]
From the last commit date, it looks like they haven't really made any
contributions to the project so they probably haven't been paying
attention.

On 2011-11-06, at 8:56, DonMcNamara
reply@reply.github.com
wrote:

**Comment by popapps** [comment]
This feature is really useful, actually essential for cloud environment... I think that would solve an issue related to ASP.NET Web Pages (Razor) and MongoDB.Web that prevents its use at the moment!

**Comment by DonMcNamara** [comment]
This feature is implemented in DLF mongo providers, here: http://code.google.com/p/mongoproviders/  (available on NuGet as well.)

I've only just started using it, but it seems to be decent.

**Comment by fjsr3000** [comment]
I think there is a problem with the last version. I'm getting this error every time:

Unable to connect to server localhost:27017: No connection could be made because the target machine actively refused it 127.0.0.1:27017.

My configuration is the following 
"< roleManager enabled='true' cacheRolesInCookie='true'" cookieTimeout='20' defaultProvider='MongoDBRoleProvider' >
      < providers >
        < clear / >
        < add name='MongoDBRoleProvider' type='MongoDB.Web.Providers.MongoDBRoleProvider' applicationName='/project' connectionStringName='mongodb://user:password@dfsdww.mongolab.com:38689/db' database='db' collection='Roles' / >
      < /providers >
    < /roleManager >"

Also when I try to run the ASPnet Configuration it shows this exception: Type is not resolved for member 'MongoDB.Driver.MongoConnectionException,MongoDB.Driver, Version=1.9.2.235, Culture=neutral, PublicKeyToken=f686731cfb9cc103'

please help

**Review by lastthyme — APPROVED** [review]

**Comment by osuritz** [comment]
Spring cleaning in the fall. This PR was open _checks calendar_ 13 years ago! Good times ^_^

**Pull request closed without merging**
